const profileTypes = {
    GET_PROFILE : 'GET_PROFILE',
    PROFILE_ERROR : 'PROFILE_ERROR',
    CLEAR_PROFILE : 'CLEAR_PROFILE',
    CREATE_PROFILE_SUCCESS : 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_FAILURE : 'CREATE_PROFILE_FAILURE',
    EDIT_PROFILE_SUCCESS : 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAILURE : 'EDIT_PROFILE_FAILURE',
    RESETE_CREATE_PROFILE_SUCCESS : 'RESETE_CREATE_PROFILE_SUCCESS',
    RESETE_CREATE_PROFILE_FAILURE : 'RESETE_CREATE_PROFILE_FAILURE',
    ADD_EXPERIENCE : 'ADD_EXPERIENCE',
    ADD_EDUCATION : 'ADD_EDUCATION',
    DELETE_PROFILE : 'DELETE_PROFILE',
    DELETE_EDUCATION : 'DELETE_EDUCATION' ,
    DELETE_EXPERIENCE : 'DELETE_EXPERIENCE',
    GET_ALL_PROFILES : 'GET_ALL_PROFILES',
    GET_REPOS : 'GET_REPOS'
}

export default profileTypes;