const userTypes = {
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILED : 'REGISTER_FAILED',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    USER_LOADED_SUCCESS : 'USER_LOADED_SUCCESS',
    LOGIN_FAILED : 'LOGIN_FAILED',
    USER_LOADED_ERROR : 'USER_LOADED_ERROR',
    LOGOUT : 'LOGOUT'
};

export default userTypes;